[tool.poetry]
name = "chat-with-your-data-solution-accelerator"
version = "1.1.0"
description = "Chat with your data solution accelerator"
authors = []
readme = "README.md"
packages = [
    { include = "code" }
]

[tool.poetry.dependencies]
python = "^3.10"
azure-functions = "1.20.0"
streamlit = "1.37.0"
python-dotenv = "1.0.1"
azure-ai-formrecognizer = "3.3.3"
azure-storage-blob = "12.20.0"
azure-identity = "1.17.1"
flask = {extras = ["async"], version = "^3.0.3"}
openai = "1.37.1"
langchain = "0.2.7"
langchain-community = "0.2.7"
langchain-openai = "0.1.16"
requests = "2.32.3"
tiktoken = "0.7.0"
azure-storage-queue = "12.11.0"
beautifulsoup4 = "4.12.3"
fake-useragent = "1.5.1"
chardet = "5.2.0"
azure-search-documents = "11.6.0b1"
azure-ai-contentsafety = "1.0.0"
python-docx = "1.1.2"
azure-keyvault-secrets = "4.8.0"
pandas = "2.2.2"
azure-monitor-opentelemetry = "^1.6.0"
opentelemetry-instrumentation-httpx = "^0.47b0"
pillow = "10.4.0"
azure-mgmt-cognitiveservices = "^13.5.0"
jsonschema = "^4.23.0"
semantic-kernel = {version = "1.3.0", python = "<3.13"}
azure-ai-ml = "^1.18.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "5.0.0"
flake8 = "7.1.0"
black = "24.4.2"
pre-commit = "3.8.0"
pytest_httpserver = "1.0.12"
trustme = "1.1.0"
jupyter = "1.0.0"
pytest-asyncio = "^0.23.8"

[tool.poetry.group.prompt-flow]
optional = true

[tool.poetry.group.prompt-flow.dependencies]
promptflow = {extras = ["azure"], version = "1.14.0"}

[tool.coverage.run]
omit = [
    "**/tests/*",
    "**/dist/*",
    "**/infra/*",
]

[tool.coverage.report]
skip_empty = true
include_namespace_packages = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
