version: "0.1"
name: rag
services:
  web:
    image: fruoccopublic.azurecr.io/rag-webapp
    ports:
      - "8080:80"
    env_file:
      - ..\.env
  admin:
    image: fruoccopublic.azurecr.io/rag-adminwebapp
    ports:
      - "8081:80"
    env_file:
      - ..\.env
  backend:
    image: fruoccopublic.azurecr.io/rag-backend
    ports: 
      - "8082:80"
    env_file:
      - ..\.env
