name: Build Docker Images

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches: [main, dev, demo]
  pull_request:
    branches: [main, dev, demo]
    types:
    - opened
    - ready_for_review
    - reopened
    - synchronize
  merge_group:

jobs:
  docker-build:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        include:
          - app_name: rag-adminwebapp
            dockerfile: docker/Admin.Dockerfile
          - app_name: rag-backend
            dockerfile: docker/Backend.Dockerfile
          - app_name: rag-webapp
            dockerfile: docker/Frontend.Dockerfile
    uses: ./.github/workflows/build-docker.yml
    with:
      registry: cwydcontainerreg.azurecr.io
      username: cwydcontainerreg
      app_name: ${{ matrix.app_name }}
      dockerfile: ${{ matrix.dockerfile }}
      push: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'dev' || github.event.workflow_run.head_branch == 'demo' }}
    secrets: inherit
