name: WebApp Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        registry: fruoccopublic.azurecr.io
        username: fruoccopublic
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker pull fruoccopublic.azurecr.io/rag-webapp:latest || true;
        docker build . --file docker/WebApp.Dockerfile --cache-from fruoccopublic.azurecr.io/rag-webapp:latest --tag fruoccopublic.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag fruoccopublic.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER fruoccopublic.azurecr.io/rag-webapp:latest;
        docker push fruoccopublic.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push fruoccopublic.azurecr.io/rag-webapp:latest;
